### ISSUE TITLE
vagrant provision fails on fresh checkout

### ISSUE THREAD

**Issue by bennytheshap** [tufts-LPC/blockytalky_elixir#35]
logfile:
==> default: Running triggers before provision...
==> default: Trying to delete folder .vagrant/machines/default/virtualbox/synced_folders
==> default: Loading Berkshelf datafile...
==> default: Sharing cookbooks with VM
==> default: Couldn't find Cheffile at ./Cheffile.
==> default: Updating Vagrant's Berkshelf...
==> default: Resolving cookbook dependencies...
==> default: Using 7-zip (1.0.2)
==> default: Using ark (0.9.0)
==> default: Using apt (2.7.0)
==> default: Using chef_handler (1.1.9)
==> default: Using build-essential (2.2.3)
==> default: Using dmg (2.2.2)
==> default: Using erlang (1.5.8)
==> default: Using elixir (0.10.0)
==> default: Using git (4.2.2)
==> default: Using github (0.3.0)
==> default: Using homebrew (1.12.0)
==> default: Using libarchive (0.5.0)
==> default: Using nodejs (2.4.0)
==> default: Using python (1.4.6)
==> default: Using windows (1.37.0)
==> default: Using yum-erlang_solutions (0.2.0)
==> default: Using yum-epel (0.6.0)
==> default: Using yum (3.6.1)
==> default: Vendoring 7-zip (1.0.2) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/7-zip
==> default: Vendoring apt (2.7.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/apt
==> default: Vendoring ark (0.9.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/ark
==> default: Vendoring build-essential (2.2.3) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/build-essential
==> default: Vendoring chef_handler (1.1.9) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/chef_handler
==> default: Vendoring dmg (2.2.2) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/dmg
==> default: Vendoring elixir (0.10.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/elixir
==> default: Vendoring erlang (1.5.8) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/erlang
==> default: Vendoring git (4.2.2) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/git
==> default: Vendoring github (0.3.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/github
==> default: Vendoring homebrew (1.12.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/homebrew
==> default: Vendoring libarchive (0.5.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/libarchive
==> default: Vendoring nodejs (2.4.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/nodejs
==> default: Vendoring python (1.4.6) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/python
==> default: Vendoring windows (1.37.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/windows
==> default: Vendoring yum (3.6.1) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/yum
==> default: Vendoring yum-epel (0.6.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/yum-epel
==> default: Vendoring yum-erlang_solutions (0.2.0) to /Users/ben/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150624-13535-1k21538-default/yum-erlang_solutions
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-08-09T17:13:12+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.3.0
==> default: [2015-08-09T17:13:13+00:00] INFO: *** Chef 12.3.0 ***
==> default: [2015-08-09T17:13:13+00:00] INFO: Chef-client pid: 2382
==> default: [2015-08-09T17:13:15+00:00] INFO: Setting the run_list to ["recipe[elixir]", "recipe[nodejs]", "recipe[git]", "recipe[python]"] from CLI options
==> default: [2015-08-09T17:13:15+00:00] INFO: Run List is [recipe[elixir], recipe[nodejs], recipe[git], recipe[python]]
==> default: [2015-08-09T17:13:15+00:00] INFO: Run List expands to [elixir, nodejs, git, python]
==> default: [2015-08-09T17:13:15+00:00] INFO: Starting Chef Run for precise64
==> default: [2015-08-09T17:13:15+00:00] INFO: Running start handlers
==> default: [2015-08-09T17:13:15+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default: Recipe: libarchive::default
==> default:   
==> default: * apt_package[libarchive-dev] action install
==> default:  (up to date)
==> default:   
==> default: Converging 41 resources
==> default: Recipe: elixir::default
==> default:   
==> default: * directory[/usr/local/lib/elixir] action delete
==> default:  (skipped due to not_if)
==> default:   
==> default: * directory[/opt/elixir] action create
==> default:  (up to date)
==> default: Recipe: apt::default
==> default:   
==> default: * file[/var/lib/apt/periodic/update-success-stamp] action nothing
==> default:  (skipped due to action :nothing)
==> default:   
==> default: * directory[/etc/apt/apt.conf.d] action create
==> default:  (up to date)
==> default:   
==> default: * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create
==> default:  (up to date)
==> default:   
==> default: * execute[apt-get-update] action run
==> default:  (skipped due to not_if)
==> default:   
==> default: * execute[apt-get update] action nothing
==> default:  (skipped due to action :nothing)
==> default:   
==> default: * execute[apt-get autoremove] action nothing
==> default:  (skipped due to action :nothing)
==> default:   
==> default: * execute[apt-get autoclean] action nothing
==> default:  (skipped due to action :nothing)
==> default:   
==> default: * execute[apt-get-update-periodic] action run
==> default:  (skipped due to only_if)
==> default:   
==> default: * directory[/var/cache/local] action create
==> default:  (up to date)
==> default:   
==> default: * directory[/var/cache/local/preseeding] action create
==> default:  (up to date)
==> default: Recipe: erlang::esl
==> default:   
==> default: * apt_repository[erlang_solutions_repo] action add
==> default:     
==> default: * remote_file[/var/chef/cache/erlang_solutions.asc] action create
==> default:  (up to date)
==> default:     
==> default: * execute[install-key erlang_solutions.asc] action run
==> default:  (skipped due to not_if)
==> default:     
==> default: * file[/var/lib/apt/periodic/update-success-stamp] action nothing
==> default:  (skipped due to action :nothing)
==> default:     
==> default: * execute[apt-cache gencaches] action nothing
==> default:  (skipped due to action :nothing)
==> default:     
==> default: * execute[apt-get update] action nothing
==> default:  (skipped due to action :nothing)
==> default:     
==> default: * file[/etc/apt/sources.list.d/erlang_solutions_repo.list] action create
==> default:  (up to date)
==> default:     
==> default:  (up to date)
==> default:   
==> default: * apt_package[esl-erlang] action install
==> default:     
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `install` on resource 'apt_package[esl-erlang]'
==> default:     
==> default: ================================================================================
==> default:     
==> default:     
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:     
==> default: ------------------------------------
==> default:     
==> default: Expected process to exit with [0], but received '100'
==> default:     
==> default: ---- Begin output of apt-get -q -y install esl-erlang=1:17.5 ----
==> default:     
==> default: STDOUT: Reading package lists...
==> default:     
==> default: Building dependency tree...
==> default:     
==> default: Reading state information...
==> default:     
==> default: Suggested packages:
==> default:     
==> default:   default-jre-headless java2-runtime-headless java1-runtime-headless
==> default:     
==> default:   java2-runtime java1-runtime
==> default:     
==> default: The following packages will be DOWNGRADED:
==> default:     
==> default:   esl-erlang
==> default:     
==> default: 0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 29 not upgraded.
==> default:     Need to get 0 B/50.2 MB of archives.
==> default:     After this operation, 0 B of additional disk space will be used.
==> default:     STDERR: E: There are problems and -y was used without --force-yes
==> default:     ---- End output of apt-get -q -y install esl-erlang=1:17.5 ----
==> default:     Ran apt-get -q -y install esl-erlang=1:17.5 returned 100
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/6e225ab2d52d0f092c7bfcac8461b4e1/cookbooks/erlang/recipes/esl.rb
==> default:     
==> default:      35:   package 'esl-erlang' do
==> default:      36:     version node['erlang']['esl']['version'] if node['erlang']['esl']['version']
==> default:      37:   end
==> default:      38: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/6e225ab2d52d0f092c7bfcac8461b4e1/cookbooks/erlang/recipes/esl.rb:35:in `from_file'
==> default:     
==> default:     apt_package("esl-erlang") do
==> default:       action :install
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       package_name "esl-erlang"
==> default:       version "1:17.5"
==> default:       timeout 900
==> default:       declared_type :package
==> default:       cookbook_name :erlang
==> default:       recipe_name "esl"
==> default:     end
==> default:     
==> default: [2015-08-09T17:13:17+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2015-08-09T17:13:17+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2015-08-09T17:13:17+00:00] ERROR: Exception handlers complete
==> default: [2015-08-09T17:13:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: Chef Client failed. 0 resources updated in 4.684204776 seconds
==> default: [2015-08-09T17:13:17+00:00] ERROR: apt_package[esl-erlang] (erlang::esl line 35) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install esl-erlang=1:17.5 ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Suggested packages:
==> default:   default-jre-headless java2-runtime-headless java1-runtime-headless
==> default:   java2-runtime java1-runtime
==> default: The following packages will be DOWNGRADED:
==> default:   esl-erlang
==> default: 0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 29 not upgraded.
==> default: Need to get 0 B/50.2 MB of archives.
==> default: After this operation, 0 B of additional disk space will be used.
==> default: STDERR: E: There are problems and -y was used without --force-yes
==> default: ---- End output of apt-get -q -y install esl-erlang=1:17.5 ----
==> default: Ran apt-get -q -y install esl-erlang=1:17.5 returned 100
==> default: [2015-08-09T17:13:17+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by mpahrens** [comment]
I am starting to feel the vagrant-ing is more trouble than it is worth. I don't know why `apt-get -q -y install esl-erlang=1:17.5` would fail on automation. 

The reason it is downgrading is likely because Erlang 18 was installed by default, but erlang shouldn't have been installed by default on a fresh vm anyways... 

It might be related to this:
https://bugs.launchpad.net/compass/+bug/1328736
try deleting the Berksfile.lock and re-provisioning

**Comment by bennytheshap** [comment]
I blew the whole thing away (vagrant destroy) 
and then it worked.

**Comment by mpahrens** [comment]
Hurray! no idea. Vagrant is buggy. It didn't work for Catherine, and was super buggy for Elena. but I got it to work first try on 5 different machines. (macbook, macbook air, lenovo, linux desktop, and my old alienware). meh
